### ISSUE TITLE
Progress Tracker

### ISSUE THREAD

**Issue by chirag-ghosh** [metakgp/chillzone#28]
Changes to be made:
- [ ] Move frontend to main repo
- [ ] Rewrite first year scraper
- [ ] Make the directory structure cleaner
- [ ] Host frontend somewhere 
- [ ] Rewrite README in the same format as gyft.

**Comment by chirag-ghosh** [comment]
I will take care of hosting when the other things are done.

**Comment by shikhar-irez** [comment]
I will work on this.

**Comment by LakshyaSatpal** [comment]
willing to work on frontend changes

**Comment by chirag-ghosh** [comment]
@LakshyaSatpal please go ahead

**Comment by proffapt** [comment]
@chirag-ghosh please update this issue tracker based on the merged pr #55
